# Generated by Django 2.0 on 2018-03-10 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OpinionMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorryCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorryMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('user_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.UserAction')),
                ('worry_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.WorryCategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorryType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorryUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='worrymessage',
            name='worry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.WorryType'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='worry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.WorryUser'),
        ),
        migrations.AddField(
            model_name='opinionmessage',
            name='user_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.UserAction'),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='opinion_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.OpinionMessage'),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='worry_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.WorryMessage'),
        ),
        migrations.AddField(
            model_name='configurationpreference',
            name='worry_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.WorryCategory'),
        ),
        migrations.AddField(
            model_name='configurationpreference',
            name='worry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.WorryUser'),
        ),
    ]
