# Generated by Django 2.0 on 2018-03-10 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinionmessage',
            name='user_action',
        ),
        migrations.RemoveField(
            model_name='worrycategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worrymessage',
            name='user_action',
        ),
        migrations.RemoveField(
            model_name='worrytype',
            name='name',
        ),
        migrations.AddField(
            model_name='configurationpreference',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='configurationpreference',
            name='status_configuration',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='opinionmessage',
            name='grade_opinion',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinionmessage',
            name='opinion_message',
            field=models.TextField(default='MY OPINION'),
        ),
        migrations.AddField(
            model_name='opinionmessage',
            name='opinion_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='opinionmessage',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='opinionmessage',
            name='status_opinion',
            field=models.CharField(default='PUBLISHED', max_length=50),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action',
            field=models.CharField(default='PUBLISH', max_length=50),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useraction',
            name='opinion_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.OpinionMessage'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='worry_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.WorryMessage'),
        ),
        migrations.AddField(
            model_name='worrycategory',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='worrycategory',
            name='observation',
            field=models.CharField(default='OBSERVATION', max_length=200),
        ),
        migrations.AddField(
            model_name='worrymessage',
            name='message_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='worrymessage',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worrymessage',
            name='status_message',
            field=models.CharField(default='PUBLISHED', max_length=50),
        ),
        migrations.AddField(
            model_name='worrymessage',
            name='worry_message',
            field=models.TextField(default='MY EXPERIENCE'),
        ),
        migrations.AddField(
            model_name='worrytype',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='worrytype',
            name='observation',
            field=models.CharField(default='OBSERVATION', max_length=200),
        ),
        migrations.AddField(
            model_name='worryuser',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='configurationpreference',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messagerecord',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='worryuser',
            name='user_name',
            field=models.CharField(default='USERNAME', max_length=100),
        ),
    ]
