# Generated by Django 2.0 on 2018-03-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180310_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionmessage',
            name='opinion_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='opinion_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.OpinionMessage'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='worry_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.WorryMessage'),
        ),
        migrations.AlterField(
            model_name='worrymessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worrymessage',
            name='message_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
